[package]
name = "network-lib"
version = "0.9.20251222"
edition = "2024"

[lib]
name = "aria_http"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
vm-lib = { path = "../../vm-lib" }
opcodes-lib = { path = "../../opcodes-lib" }
reqwest = { version = "0.13.1", features = ["blocking"] }
